-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 16:57:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Park`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Park` (
  `IdPark` INT NOT NULL AUTO_INCREMENT,
  `TotalParkingSpaces` INT NOT NULL,
  `FreeParkingSpaces` INT NOT NULL,
  PRIMARY KEY (`IdPark`),
  UNIQUE INDEX `idParque_UNIQUE` (`IdPark` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ParkingSpace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ParkingSpace` (
  `IdParkingSpace` INT NOT NULL AUTO_INCREMENT,
  `Reserved` TINYINT NOT NULL,
  `Park_IdPark` INT NOT NULL,
  PRIMARY KEY (`IdParkingSpace`, `Park_IdPark`),
  UNIQUE INDEX `idParkingSpace_UNIQUE` (`IdParkingSpace` ASC) VISIBLE,
  INDEX `fk_ParkingSpace_Park1_idx` (`Park_IdPark` ASC) VISIBLE,
  CONSTRAINT `fk_ParkingSpace_Park1`
    FOREIGN KEY (`Park_IdPark`)
    REFERENCES `mydb`.`Park` (`IdPark`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `IdUser` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `LicensePlate` VARCHAR(6) NOT NULL,
  `EntryDate` DATE NULL,
  `DepartureDate` DATE NULL,
  `Email` VARCHAR(45) NOT NULL,
  `ParkingSpace_IdParkingSpace` INT NOT NULL,
  `ParkingSpace_Park_IdPark` INT NOT NULL,
  PRIMARY KEY (`IdUser`, `ParkingSpace_IdParkingSpace`, `ParkingSpace_Park_IdPark`),
  UNIQUE INDEX `idUser_UNIQUE` (`IdUser` ASC) VISIBLE,
  UNIQUE INDEX `LicensePlate_UNIQUE` (`LicensePlate` ASC) VISIBLE,
  INDEX `fk_User_ParkingSpace1_idx` (`ParkingSpace_IdParkingSpace` ASC, `ParkingSpace_Park_IdPark` ASC) VISIBLE,
  CONSTRAINT `fk_User_ParkingSpace1`
    FOREIGN KEY (`ParkingSpace_IdParkingSpace` , `ParkingSpace_Park_IdPark`)
    REFERENCES `mydb`.`ParkingSpace` (`IdParkingSpace` , `Park_IdPark`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Request` (
  `IdRequest` INT NOT NULL AUTO_INCREMENT,
  `RequestDate` DATE NOT NULL,
  `State` INT NOT NULL,
  `User_IdUser` INT NOT NULL,
  PRIMARY KEY (`IdRequest`, `User_IdUser`),
  UNIQUE INDEX `idRequest_UNIQUE` (`IdRequest` ASC) VISIBLE,
  INDEX `fk_Request_User_idx` (`User_IdUser` ASC) VISIBLE,
  CONSTRAINT `fk_Request_User`
    FOREIGN KEY (`User_IdUser`)
    REFERENCES `mydb`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
